//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySys.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int ID_author { get; set; }
        [Required(ErrorMessage = "Моля въведете името на автора")]
        [StringLength(30, MinimumLength = 1, ErrorMessage = " Може да е до 30 символа")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Моля въведете името на автора")]
        [StringLength(30, MinimumLength = 1, ErrorMessage = " Може да е до 30 символа")]
        public string LastName { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
