//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySys.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.ReaderBorrows = new HashSet<ReaderBorrow>();
        }
    
        public int ID_book { get; set; }
        [Required(ErrorMessage = "Моля въведете заглавието на книгата")]
        [StringLength(30, MinimumLength = 1, ErrorMessage = " Може да е до 30 символа")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Моля изберете жанр")]
        public Nullable<int> ID_genre { get; set; }
        [Required(ErrorMessage = "Моля изберете автор")]
        public Nullable<int> ID_author { get; set; }
        [Required(ErrorMessage = "Моля въведете годината на публикация. Максимално до 4 символа")]
        [StringLength(4, MinimumLength = 1, ErrorMessage = " Може да е до 4 символа")]
        public string Year { get; set; }
        public Nullable<int> ID_publisher { get; set; }
        [Required(ErrorMessage = "Моля въведете брой страници. Максимално до 4 символа")]
        [StringLength(4, MinimumLength = 1, ErrorMessage = " Може да е до 4 символа")]
        public string Pages { get; set; }
        public Nullable<bool> Available { get; set; }
        [Required(ErrorMessage = "Моля въведете брой.")]
        [StringLength(4, MinimumLength = 1, ErrorMessage = " Може да е до 4 символа")]
        public Nullable<int> Stock { get; set; }
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderBorrow> ReaderBorrows { get; set; }
    }
}
