//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySys.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.News = new HashSet<News>();
            this.ReaderBorrows = new HashSet<ReaderBorrow>();
        }
        public int ID_employee { get; set; }
        [Required(ErrorMessage = "Моля въведете името на служителя.")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = " Може да е до 20 символа")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Моля въведете фамиията на служителя.")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = " Може да е до 20 символа")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Моля въведете имейл адреса си")]
        [DataType(DataType.EmailAddress)]
        [StringLength(50, MinimumLength = 1, ErrorMessage = " Може да е до 50 символа")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Моля въведете коректен имейл адрес")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Моля въведете парола.")]
        [DataType(DataType.Password)]
        [StringLength(10, MinimumLength = 1, ErrorMessage = " Може да е до 10 символа")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Моля въведете адреса.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = " Може да е до 50 символа")]
        public string Adress { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderBorrow> ReaderBorrows { get; set; }
    }
}
