//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySys.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class News
    {
        public int ID_news { get; set; }
        [Required(ErrorMessage = "Моля въведете тема. Може да е до 50 символа")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = " Може да е до 50 символа")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Моля въведете съобщението. Може да е до 500 символа")]
        [StringLength(500, MinimumLength = 1, ErrorMessage = " Може да е до 500 символа")]
        public string Article { get; set; }
        public Nullable<bool> Screen { get; set; }
        [Required(ErrorMessage = "Моля изберете служител.")]
        public Nullable<int> ID_employee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
