//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySys.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.ReaderBorrows = new HashSet<ReaderBorrow>();
        }
    
        public int ID_reader { get; set; }
        [Required(ErrorMessage = "Моля въведете името си. Може да е до 20 символа")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = " Може да е до 20 символа")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Моля въведете фамиията си. Може да е до 20 символа")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = " Може да е до 20 символа")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Моля въведете имейл адреса си. Може да е до 20 символа")]
        [DataType(DataType.EmailAddress)]
        [StringLength(20, MinimumLength = 1, ErrorMessage = " Може да е до 20 символа")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Моля въведете коректен имейл адрес.Може да е до 20 символа")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Моля въведете паролата си.Може да е до 10 символа")]
        [DataType(DataType.Password)]
        [StringLength(250, MinimumLength = 1, ErrorMessage = " Може да е до 10 символа")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Въведете телефонния си номер.Може да е до 10 символа")]
        [Phone(ErrorMessage = "Въведете телефонния си номер.Може да е до 10 символа")]
        [StringLength(10, MinimumLength = 1, ErrorMessage = " Може да е до 10 символа")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Моля въведете учебното си заведение.Може да е до 50 символа.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = " Може да е до 50 символа")]
        public string School { get; set; }
        public Nullable<bool> Activate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderBorrow> ReaderBorrows { get; set; }
    }
}
