//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySys.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReaderBorrow
    {
        public int ID_borrow { get; set; }
        [Required(ErrorMessage = "Моля изберете читател.")]
        public Nullable<int> ID_reader { get; set; }
        [Required(ErrorMessage = "Моля изберете служител.")]

        public Nullable<int> ID_employee { get; set; }
        [Required(ErrorMessage = "Моля изберете книгата.")]

        public Nullable<int> ID_book { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<bool> Process { get; set; }
        public Nullable<System.DateTime> ReturnReader { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
